### ISSUE TITLE
App Keeps crashing 

### ISSUE THREAD

**Issue by ghost** [z-huang/music#1104]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1.App crashed after playing some songs

### Expected behavior

App  shouldn't crash 

### Actual behavior

App keeps crashing after playing some songs 

### Screenshots/Screen recordings

![Screenshot_2023-10-03-16-53-29-740_com teslacoilsw launcher](https://github.com/z-huang/InnerTune/assets/101904831/444c4b13-4614-4bad-8943-161dde09680b)

### Logs

java.util.concurrent.CancellationException
	at nb.b.get(SourceFile:1)
	at b8.i0.K(Unknown Source:1)
	at l7.j.D0(SourceFile:7)
	at h5.l.a(SourceFile:704)
	at h5.l1.run(Unknown Source:12)
	at i3.g0.H(Unknown Source:25)
	at h5.f2.T(SourceFile:98)
	at h5.f2.V(SourceFile:9)
	at h5.p1$c.n0(SourceFile:20)
	at h5.f0.f(SourceFile:14)
	at i3.m.handleMessage(SourceFile:258)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8232)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:580)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1028)
Caused by: ib.k1: Parent job is Cancelled; job=m1{Cancelled}@3f8922
Caused by: java.util.concurrent.ExecutionException: java.net.SocketTimeoutException: timeout
	at v8.a$b.k(SourceFile:101)
	at ra.a.r(Unknown Source:8)
	at ob.w.D0(Unknown Source:6)
	at ib.a.r(SourceFile:23)
	at ra.a.r(Unknown Source:31)
	at ib.p0.run(Unknown Source:105)
	at ob.k$a.run(SourceFile:4)
	at qb.j.run(Unknown Source:2)
	at qb.a$a.run(SourceFile:96)
Caused by: java.net.SocketTimeoutException: timeout
	at hc.s$c.j(Unknown Source:4)
	at hc.s$c.l(Unknown Source:8)
	at hc.q.d(SourceFile:29)
	at ec.c.c(SourceFile:3)
	at fc.b.a(SourceFile:284)
	at fc.f.b(SourceFile:133)
	at ec.a.a(SourceFile:102)
	at fc.f.b(SourceFile:133)
	at cc.a.a(SourceFile:148)
	at fc.f.b(SourceFile:133)
	at fc.a.a(SourceFile:142)
	at fc.f.b(SourceFile:133)
	at fc.h.a(SourceFile:154)
	at fc.f.b(SourceFile:133)
	at ec.e.g(SourceFile:96)
	at ec.e$a.run(SourceFile:36)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)

### InnerTune version

0.5.3

### Android version

Android 13

**Comment by ghost** [comment]
I really love your app. So it'll be much appreciated if you fellas can fix this problem ,as it is very annoying.

**Comment by qraftyfied** [comment]
Same for me there. Almost unusable but Ill stick with it, hopefully it gets fixed :)

**Comment by z-huang** [comment]
Does it still happen?

**Comment by qraftyfied** [comment]
not that im aware of
