### ISSUE TITLE
App crashed randomly

### ISSUE THREAD

**Issue by NikunjK8** [z-huang/music#1170]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Just normal browsing in app

### Expected behavior

The app should keep working

### Actual behavior

The app crashed unexpectedly

### Logs

FATAL EXCEPTION: DefaultDispatcher-worker-11
Process: com.zionhuang.music, PID: 3422
ge.b: Socket timeout has expired [url=https://lyrics.kugou.com/download?fmt=lrc&charset=utf8&client=pc&ver=1&id=154803091&accesskey=245F59053FD341FCF086C0ED120B3CF5, socket_timeout=unknown] ms
	at u9.b.d(SourceFile:53)
	at fe.a.a(SourceFile:129)
	at kb.g.a(SourceFile:52)
	at bh.d$a.run(SourceFile:117)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: kg.h: [z1{Cancelling}@f5e381e, Dispatchers.IO]
Caused by: java.net.SocketTimeoutException: timeout
	at eh.s$c.j(Unknown Source:4)
	at eh.s$c.l(Unknown Source:8)
	at eh.q.c(SourceFile:29)
	at bh.b.c(SourceFile:3)
	at ch.b.a(SourceFile:272)
	at ch.f.b(SourceFile:133)
	at bh.a.a(SourceFile:102)
	at ch.f.b(SourceFile:133)
	at zg.a.a(SourceFile:146)
	at ch.f.b(SourceFile:133)
	at ch.a.a(SourceFile:136)
	at ch.f.b(SourceFile:133)
	at ch.h.a(SourceFile:154)
	at ch.f.b(SourceFile:133)
	at bh.d.e(SourceFile:96)
	at bh.d$a.run(SourceFile:36)
	... 3 more

### InnerTune version

0.5.3

### Android version

Android 12

**Comment by HatsuneAmi** [comment]
This happens to me too. I was listening to my songs on my phone and it's just turned off or on idle if we don't include Innertune, when the app just decides to say goodbye and crashes either mid-song or after a song.

This happened unusually more often today than the rest of the days and it's a bit of a bummer ngl

**Comment by z-huang** [comment]
Still happening?

**Comment by NikunjK8** [comment]
Nothing so far. Thanks for fixing it :)

**Comment by z-huang** [comment]
Hope it's the real fix.
If it's still happening, please tell me. (This is a weird bug)

**Comment by NikunjK8** [comment]
Sure. I'll report if i face it again
