### ISSUE TITLE
Account Playlist not opening

### ISSUE THREAD

**Issue by esdnm** [z-huang/music#1306]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Try opening a playlist from account section 

### Expected behavior

Playlist should load

### Actual behavior

Doesn't load, hangs on the loading screen

### Logs

Unable

### InnerTune version

0.5.3 (FOSS)

### Android version

14

### Additional information

I tried cleaning storage, and relogging to Google account on the app

**Comment by phantomwhale** [comment]
The fork at https://github.com/Malopieds/InnerTune/releases has version 0.5.8 which fixed playlist / album loading issues for me. The discussion on #1295 covers this bug.

I've moved over to that fork (which has active development; kudos to @Malopieds) and away from this release (which appears to be no longer working now; but kudos to @z-huang for all his work underpinning the new fork)

**Comment by KOLADIYAYASH** [comment]
java.lang.UnsupportedOperationException: Unknown item type
	at com.zionhuang.innertube.models.MusicTwoRowItemRenderer.a(SourceFile:471)
	at com.zionhuang.innertube.models.SectionListRenderer$Content.a(SourceFile:95)
	at com.zionhuang.innertube.models.response.BrowseResponse.a(SourceFile:214)
	at x7.h.a(SourceFile:205)
	at x7.h$b.u(Unknown Source:12)
	at va.a.m(Unknown Source:8)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at ga.i.e(SourceFile:71)
	at ga.i.d(SourceFile:16)
	at ga.i$a.m(SourceFile:25)
	at va.a.m(Unknown Source:31)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)

**Comment by LightslicerGP** [comment]
> The fork at https://github.com/Malopieds/InnerTune/releases has version 0.5.8 which fixed playlist / album loading issues for me. The discussion on #1295 covers this bug.
> 
> I've moved over to that fork (which has active development; kudos to @Malopieds) and away from this release (which appears to be no longer working now; but kudos to @z-huang for all his work underpinning the new fork)

Thank you so much! I thought this repo was deprecated and would've never been worked on again, lifesaver!

**Comment by phantomwhale** [comment]
Actually @LightslicerGP I can see @z-huang has been merging a tonne of changes onto the development branch today, including the fixes from @Malopieds, so I suspect we're going to see a working release back onto this repo in the very near future 🎉

**Comment by LightslicerGP** [comment]
> Actually @LightslicerGP I can see @z-huang has been merging a tonne of changes onto the development branch today, including the fixes from @Malopieds, so I suspect we're going to see a working release back onto this repo in the very near future 🎉 

0.5.4 just released! Lmao 😭

**Comment by ruskcoder** [comment]
It still doesn't work for me... I have no clue why. These are the logs. 

2024-08-06 14:01:09.985 18962-18962 ViewRootIm...nActivity] com.zionhuang.music.debug            I  ViewPostIme pointer 0
2024-08-06 14:01:10.017 18962-18962 ViewRootIm...nActivity] com.zionhuang.music.debug            I  ViewPostIme pointer 1
2024-08-06 14:01:10.504 18962-19087 System.err              com.zionhuang.music.debug            W  java.lang.NullPointerException
2024-08-06 14:01:10.504 18962-19087 System.err              com.zionhuang.music.debug            W  	at com.zionhuang.innertube.YouTube.playlist-gIAlu-s(YouTube.kt:255)
2024-08-06 14:01:10.504 18962-19087 System.err              com.zionhuang.music.debug            W  	at com.zionhuang.innertube.YouTube$playlist$1.invokeSuspend(Unknown Source:15)
2024-08-06 14:01:10.504 18962-19087 System.err              com.zionhuang.music.debug            W  	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
2024-08-06 14:01:10.505 18962-19087 System.err              com.zionhuang.music.debug            W  	at 

line 255:
title = header?.title?.runs?.firstOrNull()?.text!!,

sorry for using light mode
![image](https://github.com/user-attachments/assets/81a90050-ae58-4f49-a41f-8d339ed8da13)

**Comment by z-huang** [comment]
Fixed by #1319
