### ISSUE TITLE
App crashes when opening Playlists/Artists

### ISSUE THREAD

**Issue by filinux13** [z-huang/music#1346]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

- Go to Playlists
- Open the >9th.. playlist (sometimes 9th opens, but 10th and so on always crashes)

### Expected behavior

The playlist should be shown

### Actual behavior

The app Crashes, but you actualy play the playlist, going on the 3 dots and then play.

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/5fce9f1c-ae26-4edb-9c81-7726fb18901e

### Logs
java.lang.IllegalStateException: Size(720 x -49) is out of range. Each dimension must be between 0 and 16777215.
	at q0.L.w(SourceFile:38)
	at H.y.b(SourceFile:244)
	at q0.t.a(SourceFile:38)
	at b0.I.i(SourceFile:1)
	at q0.y.a(SourceFile:11)
	at u.G.i(SourceFile:59)
	at q0.c.i(SourceFile:10)
	at q0.y.a(SourceFile:11)
	at f1.v.d(SourceFile:363)
	at T.s.d(SourceFile:60)
	at T.v.a(SourceFile:52)
	at T.w.c(SourceFile:153)
	at q0.d0.a(SourceFile:3)
	at q0.H.B0(SourceFile:129)
	at q0.H.a(SourceFile:96)
	at u.t.b(SourceFile:82)
	at q0.t.a(SourceFile:38)
	at b0.I.i(SourceFile:1)
	at q0.y.a(SourceFile:11)
	at f1.v.d(SourceFile:363)
	at T.s.d(SourceFile:60)
	at T.v.a(SourceFile:52)
	at T.w.c(SourceFile:153)
	at q0.d0.a(SourceFile:3)
	at q0.H.B0(SourceFile:129)
	at q0.H.a(SourceFile:96)
	at u.t.b(SourceFile:214)
	at q0.t.a(SourceFile:38)
	at u.B.i(SourceFile:97)
	at q0.y.a(SourceFile:11)
	at f1.v.d(SourceFile:363)
	at T.s.d(SourceFile:60)
	at T.v.a(SourceFile:52)
	at T.w.c(SourceFile:153)
	at q0.d0.a(SourceFile:3)
	at q0.H.B0(SourceFile:129)
	at q0.H.a(SourceFile:96)
	at u.t.b(SourceFile:82)
	at q0.t.a(SourceFile:38)
	at b0.l.i(SourceFile:1)
	at q0.y.a(SourceFile:11)
	at f1.v.d(SourceFile:363)
	at T.s.d(SourceFile:60)
	at T.v.a(SourceFile:52)
	at T.w.c(SourceFile:153)
	at q0.d0.a(SourceFile:3)
	at q0.H.B0(SourceFile:129)
	at q0.H.a(SourceFile:96)
	at u.t.b(SourceFile:214)
	at q0.t.a(SourceFile:38)
	at f1.v.d(SourceFile:363)
	at T.s.d(SourceFile:60)
	at T.v.a(SourceFile:52)
	at T.w.c(SourceFile:153)
	at q0.d0.a(SourceFile:3)
	at q0.H.B0(SourceFile:129)
	at q0.O.d(SourceFile:55)
	at q0.O.l(SourceFile:124)
	at q0.O.i(SourceFile:87)
	at r0.s.t(SourceFile:36)
	at r0.s.dispatchDraw(SourceFile:15)
	at android.view.View.draw(View.java:23430)
	at android.view.View.updateDisplayListIfDirty(View.java:22262)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
	at android.view.View.updateDisplayListIfDirty(View.java:22202)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
	at android.view.View.updateDisplayListIfDirty(View.java:22202)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
	at android.view.View.updateDisplayListIfDirty(View.java:22202)
	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
	at android.view.View.updateDisplayListIfDirty(View.java:22202)
	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5048)
	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4749)
	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3912)
	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2610)
	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9619)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1491)
	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1499)
	at android.view.Choreographer.doCallbacks(Choreographer.java:1114)
	at android.view.Choreographer.doFrame(Choreographer.java:1031)
	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1467)
	at android.os.Handler.handleCallback(Handler.java:942)
	at android.os.Handler.dispatchMessage(Handler.java:99)
	at android.os.Looper.loopOnce(Looper.java:211)
	at android.os.Looper.loop(Looper.java:300)
	at android.app.ActivityThread.main(ActivityThread.java:8410)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)

### InnerTune version

0.5.5

### Android version

Android 13

### Additional information

Redmi 10C MIUI 14.0.6

**Comment by Username1-a** [comment]
Sometimes opening playlist crashing for me too on version 0.5.5 upon opening the app
(Just in case, I did backup restore from Malopieds fork with this method https://github.com/z-huang/InnerTune/discussions/1310#discussioncomment-10268662), then after force stopping the app a couple of times it's no longer crashes

**Comment by z-huang** [comment]
I experienced the problem, too. The log may be this:
```
Fatal Exception: java.lang.IllegalStateException
Size(720 x -68) is out of range. Each dimension must be between 0 and 16777215.
```
and may be originated from `TopAppBar`.

I'm trying to use the SearchBar provided from the material3 library, and hope it can fix the issue.

**Comment by z-huang** [comment]
Does anyone know how to produce the bug?

**Comment by filinux13** [comment]
> The log may be this:...

I checked the logs and i was like that for me too. (i edited if you want to check it)

> Does anyone know how to produce the bug?

For me, it always happens when i click on the lasts playlist, i have like 20 playlists with 30 songs, the firsts playlists always opens ok, but the others crash, i have to invert the playlist order to open the others and it works

**Comment by filinux13** [comment]
I also noticed the app crashes seeing SOME artists when clicking the name. 
Same crash log:
> java.lang.IllegalStateException: Size(720 x -49) is out of range. Each dimension must be between 0 and 16777215

https://github.com/user-attachments/assets/7c010bf5-c4bf-44e6-a9e4-209984dfce43

As shown in the video you can see the artist fine by clicking on the 3 dots and artist

**Comment by z-huang** [comment]
Please check the fix.
Quite annoying bug. Will make a new release soon.

**Comment by filinux13** [comment]
Sadly, this fix didn't solve my issue.

Log:

>
>      java.lang.IllegalStateException: Size(720 x -393) is out of range. Each dimension must be between 0 and 16777215.
> 	at android.support.v4.media.session.b.U(SourceFile:3)
> 	at y0.M.c0(SourceFile:50)
> 	at w0.M.k(SourceFile:1)
> 	at K.y.b(SourceFile:258)
> 	at y0.t.b(SourceFile:38)
> 	at v.Z.f(SourceFile:117)
> 	at y0.y.b(SourceFile:15)
> 	at g0.W.f(SourceFile:1)
> 	at y0.y.b(SourceFile:15)
> 	at v.I.f(SourceFile:59)
> 	at y0.c.f(SourceFile:10)
> 	at y0.y.b(SourceFile:15)
> 	at W.b.f(SourceFile:11)
> 	at W.b.d(SourceFile:33)
> 	at E4.b.W(SourceFile:56)
> 	at X.v.a(SourceFile:52)
> 	at X.w.c(SourceFile:140)
> 	at y0.f0.a(SourceFile:3)
> 	at y0.J.H0(SourceFile:132)
> 	at y0.J.b(SourceFile:91)
> 	at v.u.b(SourceFile:84)
> 	at y0.t.b(SourceFile:38)
> 	at g0.W.f(SourceFile:1)
> 	at y0.y.b(SourceFile:15)
> 	at W.b.f(SourceFile:11)
> 	at W.b.d(SourceFile:33)
> 	at E4.b.W(SourceFile:56)
> 	at X.v.a(SourceFile:52)
> 	at X.w.c(SourceFile:140)
> 	at y0.f0.a(SourceFile:3)
> 	at y0.J.H0(SourceFile:132)
> 	at y0.J.b(SourceFile:91)
> 	at v.u.b(SourceFile:255)
> 	at y0.t.b(SourceFile:38)
> 	at v.D.f(SourceFile:97)
> 	at y0.y.b(SourceFile:15)
> 	at W.b.f(SourceFile:11)
> 	at W.b.d(SourceFile:33)
> 	at E4.b.W(SourceFile:56)
> 	at X.v.a(SourceFile:52)
> 	at X.w.c(SourceFile:140)
> 	at y0.f0.a(SourceFile:3)
> 	at y0.J.H0(SourceFile:132)
> 	at y0.J.b(SourceFile:91)
> 	at o.p.b(SourceFile:24)
> 	at y0.t.b(SourceFile:38)
> 	at o.E.f(SourceFile:242)
> 	at y0.y.b(SourceFile:15)
> 	at g0.q.f(SourceFile:1)
> 	at y0.y.b(SourceFile:15)
> 	at C.f1.g(SourceFile:77)
> 	at w0.x.f(SourceFile:8)
> 	at y0.y.b(SourceFile:15)
> 	at W.b.f(SourceFile:11)
> 	at W.b.d(SourceFile:33)
> 	at E4.b.W(SourceFile:56)
> 	at X.v.a(SourceFile:52)
> 	at X.w.c(SourceFile:140)
> 	at y0.f0.a(SourceFile:3)
> 	at y0.J.H0(SourceFile:132)
> 	at y0.J.b(SourceFile:91)
> 	at o.j.b(SourceFile:58)
> 	at y0.t.b(SourceFile:38)
> 	at o.n.f(SourceFile:1)
> 	at y0.c.f(SourceFile:10)
> 	at y0.y.b(SourceFile:15)
> 	at g0.W.f(SourceFile:1)
> 	at y0.y.b(SourceFile:15)
> 	at W.b.f(SourceFile:11)
> 	at W.b.d(SourceFile:33)
> 	at E4.b.W(SourceFile:114)
> 	at X.v.a(SourceFile:52)
> 	at X.w.c(SourceFile:140)
> 	at y0.f0.a(SourceFile:3)
> 	at y0.J.H0(SourceFile:132)
> 	at y0.D.M(SourceFile:17)
> 	at y0.D.N(SourceFile:18)
> 	at y0.P.c(SourceFile:8)
> 	at y0.P.m(SourceFile:138)
> 	at y0.P.j(SourceFile:90)
> 	at z0.s.v(SourceFile:36)
> 	at z0.s.dispatchDraw(SourceFile:15)
> 	at android.view.View.draw(View.java:23430)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22262)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22202)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22202)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22202)
> 	at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4566)
> 	at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4539)
> 	at android.view.View.updateDisplayListIfDirty(View.java:22202)
> 	at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:682)
> 	at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:690)
> 	at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:798)
> 	at android.view.ViewRootImpl.draw(ViewRootImpl.java:5048)
> 	at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:4749)
> 	at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:3912)
> 	at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:2610)
> 	at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:9619)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1491)
> 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1499)
> 	at android.view.Choreographer.doCallbacks(Choreographer.java:1114)
> 	at android.view.Choreographer.doFrame(Choreographer.java:1031)
> 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1467)
> 	at android.os.Handler.handleCallback(Handler.java:942)
> 	at android.os.Handler.dispatchMessage(Handler.java:99)
> 	at android.os.Looper.loopOnce(Looper.java:211)
> 	at android.os.Looper.loop(Looper.java:300)
> 	at android.app.ActivityThread.main(ActivityThread.java:8410)
> 	at java.lang.reflect.Method.invoke(Native Method)
> 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:559)
> 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:954)
> 

*Edit: Ignore this, for some reason is it working now, but i will keep this comment here. Thanks for fixing it!
