### ISSUE TITLE
The application crashes after importing the backup 

### ISSUE THREAD

**Issue by Derpachi** [z-huang/music#1357]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Open app
2. Open Settings
3. Import backup
4. App crashing

### Expected behavior

Not crashing

### Actual behavior

It's crash

### Screenshots/Screen recordings

https://github.com/user-attachments/assets/fe69ad47-a85a-4d8d-ab32-0587973747e0

### Logs

This information is generated from the Crash Log View application. - https://play.google.com/store/apps/details?id=com.arumcomm.crashlogviewer

Process: com.zionhuang.music
PID: 29013
UID: 10260
Frozen: false
Flags: 0x20c8be44
Package: com.zionhuang.music v22 (0.5.6)
Foreground: Yes
Process-Runtime: 3743
Build: TECNO/CK8n-RU/TECNO-CK8n:14/UP1A.231005.007/240529V354:user/release-keys
Crash-Handler: e5.t
Loading-Progress: 1.0
Dropped-Count: 0

java.lang.IllegalStateException: A migration from 14 to 12 was required but not found. Please provide the necessary Migration path via RoomDatabase.Builder.addMigration(Migration ...) or allow for destructive migrations via one of the RoomDatabase.Builder.fallbackToDestructiveMigration* methods.
	at B.q0.D(SourceFile:428)
	at B.q0.B(SourceFile:1)
	at m3.f.onDowngrade(SourceFile:15)
	at android.database.sqlite.SQLiteOpenHelper.getDatabaseLocked(SQLiteOpenHelper.java:414)
	at android.database.sqlite.SQLiteOpenHelper.getWritableDatabase(SQLiteOpenHelper.java:316)
	at m3.f.d(SourceFile:5)
	at m3.f.e(SourceFile:64)
	at m3.f.a(SourceFile:24)
	at m3.g.getWritableDatabase(SourceFile:10)
	at com.zionhuang.music.db.InternalDatabase.c(SourceFile:11)
	at G6.y.n(SourceFile:7)
	at G6.y.call(SourceFile:297)
	at h3.b.t(SourceFile:81)
	at X7.a.n(SourceFile:9)
	at o8.K.run(SourceFile:95)
	at h1.m.run(SourceFile:264)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
	at java.lang.Thread.run(Thread.java:1012)
	Suppressed: u8.g: [v0{Cancelling}@f5a1ee2, Dispatchers.Main]

### InnerTune version

0.5.6

### Android version

Android 14

**Comment by z-huang** [comment]
You may be migrating from @Malopieds's fork. If so, check out this tool to migrate your database: https://github.com/7heMech/InnerTune-Backup-Fix
