### ISSUE TITLE
No stream available errors after Seedvault restore

### ISSUE THREAD

**Issue by lucasmz-dev** [z-huang/music#1623]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Restore a big DB with Seedvault / google backups

### Expected behavior

Everything is kept just fine

### Actual behavior

A few songs no longer can be played

### Logs

```
09-28 03:10:42.366  1825  1825 E AS.MusicFxHelper: Audio session 1313 already open for UID: 10258, package: com.zionhuang.music.debug, abort
09-28 03:10:42.372  3408  3408 E AudioSystem: Function: isSourceActive Line: 1533 Failed 
09-28 03:10:42.372  3408  3408 E AudioSystem: Function: isSourceActive Line: 1533 Failed 
09-28 03:10:42.390  3408  3941 E AudioEffect: set(): AudioFlinger could not create effect 0bed4300-ddd6-11db-8f34-0002a5d5c51b / ec7178ec-e5e1-4432-a3f4-4657e6795210, status: -38
09-28 03:10:42.390  3408  3941 E AudioEffects-JNI: AudioEffect initCheck failed -3
09-28 03:10:42.391  3408  3941 E AudioEffect-JAVA: Error code -3 when initializing AudioEffect.
09-28 03:10:42.391  3408  3941 E AudioFx-EffectSet: error creatingEffectSet (AndroidEffects) [  mSessionId: 1313 mDeviceInfo: android.media.AudioDeviceInfo@22 mGlobalEnabled: false ], releasing and throwing!
09-28 03:10:42.392  3408  3941 E AudioFxService: couldn't create effects for session id: 1313
09-28 03:10:42.392  3408  3941 E AudioFxService: java.lang.RuntimeException: Cannot initialize effect engine for type: 0bed4300-ddd6-11db-8f34-0002a5d5c51b Error: -3
09-28 03:10:42.392  3408  3941 E AudioFxService:        at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:543)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:501)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at android.media.audiofx.AudioEffect.<init>(AudioEffect.java:475)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at android.media.audiofx.Equalizer.<init>(Equalizer.java:139)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at org.lineageos.audiofx.backends.EffectSetWithAndroidEq.onCreate(EffectSetWithAndroidEq.java:39)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at org.lineageos.audiofx.backends.AndroidEffects.onCreate(AndroidEffects.java:53)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at org.lineageos.audiofx.backends.EffectSet.<init>(EffectSet.java:40)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at org.lineageos.audiofx.backends.EffectSetWithAndroidEq.<init>(EffectSetWithAndroidEq.java:34)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at org.lineageos.audiofx.backends.AndroidEffects.<init>(AndroidEffects.java:48)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at org.lineageos.audiofx.backends.EffectsFactory.createEffectSet(EffectsFactory.java:22)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at org.lineageos.audiofx.service.SessionManager$AudioServiceHandler.handleMessage(SessionManager.java:300)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at android.os.Handler.dispatchMessage(Handler.java:103)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at android.os.Looper.loopOnce(Looper.java:232)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at android.os.Looper.loop(Looper.java:317)
09-28 03:10:42.392  3408  3941 E AudioFxService:        at android.os.HandlerThread.run(HandlerThread.java:85)
09-28 03:10:42.760  6470  8047 E LoadTask: Unexpected exception loading stream
09-28 03:10:42.760  6470  8047 E LoadTask:   androidx.media3.common.PlaybackException: Nenhum canal de reprodução disponível
09-28 03:10:42.760  6470  8047 E LoadTask:       at com.zionhuang.music.playback.MusicService.createDataSourceFactory$lambda$36(MusicService.kt:689)
09-28 03:10:42.760  6470  8047 E LoadTask:       at com.zionhuang.music.playback.MusicService.$r8$lambda$mEm3ksxFlHMtAunGpHpRoCpwVY8(Unknown Source:0)
09-28 03:10:42.760  6470  8047 E LoadTask:       at com.zionhuang.music.playback.MusicService$$ExternalSyntheticLambda5.resolveDataSpec(D8$$SyntheticClass:0)
09-28 03:10:42.760  6470  8047 E LoadTask:       at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:108)
09-28 03:10:42.760  6470  8047 E LoadTask:       at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
09-28 03:10:42.760  6470  8047 E LoadTask:       at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1045)
09-28 03:10:42.760  6470  8047 E LoadTask:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
09-28 03:10:42.760  6470  8047 E LoadTask:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-28 03:10:42.760  6470  8047 E LoadTask:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-28 03:10:42.760  6470  8047 E LoadTask:       at java.lang.Thread.run(Thread.java:1012)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal: Playback error
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:   androidx.media3.exoplayer.ExoPlaybackException: Source error
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleIoException(ExoPlayerImplInternal.java:736)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.ExoPlayerImplInternal.handleMessage(ExoPlayerImplInternal.java:712)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at android.os.Handler.dispatchMessage(Handler.java:103)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at android.os.Looper.loopOnce(Looper.java:232)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at android.os.Looper.loop(Looper.java:317)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at android.os.HandlerThread.run(HandlerThread.java:85)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:   Caused by: androidx.media3.exoplayer.upstream.Loader$UnexpectedLoaderException: Unexpected PlaybackException: Nenhum canal de reprodução disponível
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:442)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at java.lang.Thread.run(Thread.java:1012)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:   Caused by: androidx.media3.common.PlaybackException: Nenhum canal de reprodução disponível
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at com.zionhuang.music.playback.MusicService.createDataSourceFactory$lambda$36(MusicService.kt:689)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at com.zionhuang.music.playback.MusicService.$r8$lambda$mEm3ksxFlHMtAunGpHpRoCpwVY8(Unknown Source:0)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at com.zionhuang.music.playback.MusicService$$ExternalSyntheticLambda5.resolveDataSpec(D8$$SyntheticClass:0)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:108)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1045)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
09-28 03:10:42.770  6470  6568 E ExoPlayerImplInternal:       ... 3 more
09-28 03:10:43.016  2561  2646 E MediaBrowser: onConnectFailed for ComponentInfo{com.zionhuang.music.debug/com.zionhuang.music.playback.MusicService}
09-28 03:10:43.020  2561  2646 E MediaResumeListener: Cannot resume with ComponentInfo{com.zionhuang.music.debug/com.zionhuang.music.playback.MusicService}
09-28 03:10:45.397  1825 22323 E AppOps  : Operation not found: uid=1041 pkg=audioserver(null) op=WAKE_LOCK
```

### InnerTune version

0.5.10

### Android version

Android 14, CalyxOS 5.11.2

### Additional information

It could that this was already an issue and I can only just notice it now after restoring because downloads were removed.

**Comment by lucasmz-dev** [comment]
I unfortunately did not have a regular backup... ugh

**Comment by lucasmz-dev** [comment]
[song.db.zip](https://github.com/user-attachments/files/17172922/song.db.zip)

song.db extracted from in-app backup

**Comment by lucasmz-dev** [comment]
These show up when downloading: 
```
09-28 02:46:28.100 21889 21968 E DownloadManager: Task failed: null:vrJgxiW57n4, false
09-28 02:46:28.100 21889 21968 E DownloadManager:   java.lang.NullPointerException
09-28 02:46:28.100 21889 21968 E DownloadManager:       at J2.j.m(SourceFile:461)
09-28 02:46:28.100 21889 21968 E DownloadManager:       at W1.E.h(SourceFile:3)
09-28 02:46:28.100 21889 21968 E DownloadManager:       at W1.G.h(SourceFile:3)
09-28 02:46:28.100 21889 21968 E DownloadManager:       at X1.e.l(SourceFile:269)
09-28 02:46:28.100 21889 21968 E DownloadManager:       at X1.e.h(SourceFile:168)
09-28 02:46:28.100 21889 21968 E DownloadManager:       at h2.o.b(SourceFile:266)
09-28 02:46:28.100 21889 21968 E DownloadManager:       at h2.o.run(SourceFile:25)
09-28 02:46:28.100 21889 21968 E DownloadManager:       at h2.p.a(SourceFile:16)
09-28 02:46:28.100 21889 21968 E DownloadManager:       at h2.h.run(SourceFile:40)
09-28 02:46:28.800 21889 21968 E DownloadManager: Task failed: null:p0g0Emv9oDw, false
09-28 02:46:28.800 21889 21968 E DownloadManager:   java.lang.NullPointerException
09-28 02:46:28.800 21889 21968 E DownloadManager:       at J2.j.m(SourceFile:461)
09-28 02:46:28.800 21889 21968 E DownloadManager:       at W1.E.h(SourceFile:3)
09-28 02:46:28.800 21889 21968 E DownloadManager:       at W1.G.h(SourceFile:3)
09-28 02:46:28.800 21889 21968 E DownloadManager:       at X1.e.l(SourceFile:269)
09-28 02:46:28.800 21889 21968 E DownloadManager:       at X1.e.h(SourceFile:168)
09-28 02:46:28.800 21889 21968 E DownloadManager:       at h2.o.b(SourceFile:266)
09-28 02:46:28.800 21889 21968 E DownloadManager:       at h2.o.run(SourceFile:25)
09-28 02:46:28.800 21889 21968 E DownloadManager:       at h2.p.a(SourceFile:16)
09-28 02:46:28.800 21889 21968 E DownloadManager:       at h2.h.run(SourceFile:40)
09-28 02:46:31.319 21889 21968 E DownloadManager: Task failed: null:ZQUjCT0zLt0, false
09-28 02:46:31.319 21889 21968 E DownloadManager:   java.lang.NullPointerException
09-28 02:46:31.319 21889 21968 E DownloadManager:       at J2.j.m(SourceFile:461)
09-28 02:46:31.319 21889 21968 E DownloadManager:       at W1.E.h(SourceFile:3)
09-28 02:46:31.319 21889 21968 E DownloadManager:       at W1.G.h(SourceFile:3)
09-28 02:46:31.319 21889 21968 E DownloadManager:       at X1.e.l(SourceFile:269)
09-28 02:46:31.319 21889 21968 E DownloadManager:       at X1.e.h(SourceFile:168)
09-28 02:46:31.319 21889 21968 E DownloadManager:       at h2.o.b(SourceFile:266)
09-28 02:46:31.319 21889 21968 E DownloadManager:       at h2.o.run(SourceFile:25)
09-28 02:46:31.319 21889 21968 E DownloadManager:       at h2.p.a(SourceFile:16)
09-28 02:46:31.319 21889 21968 E DownloadManager:       at h2.h.run(SourceFile:40)
09-28 02:46:31.801 21889 21968 E DownloadManager: Task failed: null:vTNXRFSpGIw, false
09-28 02:46:31.801 21889 21968 E DownloadManager:   java.lang.NullPointerException
09-28 02:46:31.801 21889 21968 E DownloadManager:       at J2.j.m(SourceFile:461)
09-28 02:46:31.801 21889 21968 E DownloadManager:       at W1.E.h(SourceFile:3)
09-28 02:46:31.801 21889 21968 E DownloadManager:       at W1.G.h(SourceFile:3)
09-28 02:46:31.801 21889 21968 E DownloadManager:       at X1.e.l(SourceFile:269)
09-28 02:46:31.801 21889 21968 E DownloadManager:       at X1.e.h(SourceFile:168)
09-28 02:46:31.801 21889 21968 E DownloadManager:       at h2.o.b(SourceFile:266)
09-28 02:46:31.801 21889 21968 E DownloadManager:       at h2.o.run(SourceFile:25)
09-28 02:46:31.801 21889 21968 E DownloadManager:       at h2.p.a(SourceFile:16)
09-28 02:46:31.801 21889 21968 E DownloadManager:       at h2.h.run(SourceFile:40)
```
