### ISSUE TITLE
Unknown error when attempting to play music

### ISSUE THREAD

**Issue by ihaadi** [z-huang/music#1645]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

- Open the app.
- On the home page, click on any music track.
- A red icon appears on the track image in the mini player.
- Click on the mini player, and you will see an "Unknown error" message along with an error icon.
- The music does not play.

### Expected behavior

The selected music should play without displaying any errors.

### Actual behavior

A red icon appears on the track in the mini player, and clicking the mini player results in an "Unknown error" message. The music does not play.

### Screenshots/Screen recordings

![1](https://github.com/user-attachments/assets/a31b9b3e-30f4-401a-b888-d912f4c58ea3)
![2](https://github.com/user-attachments/assets/ac8cb86a-3054-4fa6-ba59-266be4c90e52)

### Logs

Unexpected exception loading stream
                                                                                                      androidx.media3.common.PlaybackException: Unknown error
                                                                                                          at com.zionhuang.music.playback.MusicService.createDataSourceFactory$lambda$35(MusicService.kt:639)
                                                                                                          at com.zionhuang.music.playback.MusicService.$r8$lambda$sL6KryZX2JTGU40UEw4u6xwiCAg(Unknown Source:0)
                                                                                                          at com.zionhuang.music.playback.MusicService$$ExternalSyntheticLambda4.resolveDataSpec(D8$$SyntheticClass:0)
                                                                                                          at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:108)
                                                                                                          at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
                                                                                                          at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1045)
                                                                                                          at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
                                                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
                                                                                                          at java.lang.Thread.run(Thread.java:1012)
                                                                                                      Caused by: io.ktor.client.plugins.ServerResponseException: Server error(GET https://pipedapi.kavin.rocks/streams/heddkuA_rTY: 500 . Text: "{"error":"org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: \"Sign in to confirm that you're not a bot\"\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.checkPlayabilityStatus(YoutubeStreamExtractor.java:898)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:784)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:67)\n\tat me.kavin.piped.server.handlers.StreamHandlers.lambda$streamsResponse$0(StreamHandlers.java:54)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\tat java.base/java.lang.VirtualThread.run(VirtualThread.java:329)\n","message":"Got error: \"Sign in to confirm that you're not a bot\""}"
                                                                                                          at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:55)
                                                                                                          at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

### InnerTune version

0.5.10

### Android version

Android Studio Koala

**Comment by seenilk** [comment]
Same issue

**Comment by MLZ94** [comment]
Same issue on 2 different devices

**Comment by Hazhi-Hassan** [comment]
Same issue and it is bothering me a lot. This is what I have found:

I have 44 songs in my download list. If I try to add another song or play one, it gives me the same error. However, if I delete one song, the app goes back to normal. I am using Android on Nothing 2a

Hope it gets fixed!

**Comment by ihaadi** [comment]
It's now resolved on my end. Does the problem still persist for you?

**Comment by z-huang** [comment]
See #1653

**Comment by Mizumiyaakio** [comment]
I think this is actually cuz by YouTube Music. I just try another app call RiTune(Vimusic fork) and when I sign in my Google acc, give same error, but this app have option to play without sign in Google acc. Could be google know about this
