### ISSUE TITLE
No track is played.

### ISSUE THREAD

**Issue by Mancho970** [z-huang/music#1680]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

I just can't play any track. The software seems to work well, but I only see the dancing istograms when I choose a track, but if I enter the track detail, I see the time bar doesn't work and the timer remains to zero, and, of course, no audio comes out from the speaker.

### Expected behavior

Music reproduction

### Actual behavior

No music

### Logs

None

### InnerTune version

0.5.10

### Android version

Android 13

**Comment by Vasanthanx** [comment]
vb.d: Field 'playlistId' is required for type with serial name 'com.zionhuang.innertube.models.PlaylistPanelRenderer', but it was missing at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer
	at ac.x.i0(SourceFile:110)
	at zb.a.c(SourceFile:25)
	at ba.c.b(SourceFile:105)
	at ba.c$a.r(Unknown Source:12)
	at wa.a.n(Unknown Source:8)
	at lb.n0.run(Unknown Source:100)
	at qb.h.run(Unknown Source:12)
	at rb.j.run(Unknown Source:2)
	at rb.a$a.run(SourceFile:82)
Caused by: vb.d: Field 'playlistId' is required for type with serial name 'com.zionhuang.innertube.models.PlaylistPanelRenderer', but it was missing at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer
	at ac.x.i0(SourceFile:110)
	at androidx.fragment.app.z.a0(Unknown Source:10)
	at ac.x.a0(SourceFile:45)
	at com.zionhuang.innertube.models.response.NextResponse$a.d(SourceFile:64)
	at ac.x.i0(SourceFile:68)
	... 8 more
Caused by: vb.d: Field 'playlistId' is required for type with serial name 'com.zionhuang.innertube.models.PlaylistPanelRenderer', but it was missing at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer
	at ac.x.i0(SourceFile:110)
	at androidx.fragment.app.z.a0(Unknown Source:10)
	at ac.x.a0(SourceFile:45)
	at com.zionhuang.innertube.models.response.NextResponse$Contents$a.d(SourceFile:32)
	at ac.x.i0(SourceFile:68)
	... 12 more
Caused by: vb.d: Field 'playlistId' is required for type with serial name 'com.zionhuang.innertube.models.PlaylistPanelRenderer', but it was missing at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer
	at ac.x.i0(SourceFile:110)
	at androidx.fragment.app.z.a0(Unknown Source:10)
	at ac.x.a0(SourceFile:45)
	at com.zionhuang.innertube.models.response.NextResponse$Contents$SingleColumnMusicWatchNextResultsRenderer$a.d(SourceFile:32)
	at ac.x.i0(SourceFile:68)
	... 16 more
Caused by: vb.d: Field 'playlistId' is required for type with serial name 'com.zionhuang.innertube.models.PlaylistPanelRenderer', but it was missing at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer
	at ac.x.i0(SourceFile:110)
	at androidx.fragment.app.z.a0(Unknown Source:10)
	at ac.x.a0(SourceFile:45)
	at com.zionhuang.innertube.models.response.NextResponse$Contents$SingleColumnMusicWatchNextResultsRenderer$TabbedRenderer$a.d(SourceFile:32)
	at ac.x.i0(SourceFile:68)
	... 20 more
Caused by: vb.d: Field 'playlistId' is required for type with serial name 'com.zionhuang.innertube.models.PlaylistPanelRenderer', but it was missing at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer
	at ac.x.i0(SourceFile:110)
	at androidx.fragment.app.z.a0(Unknown Source:10)
	at ac.x.a0(SourceFile:45)
	at com.zionhuang.innertube.models.response.NextResponse$Contents$SingleColumnMusicWatchNextResultsRenderer$TabbedRenderer$WatchNextTabbedResultsRenderer$a.d(SourceFile:37)
	at ac.x.i0(SourceFile:68)
	... 24 more
Caused by: vb.d: Field 'playlistId' is required for type with serial name 'com.zionhuang.innertube.models.PlaylistPanelRenderer', but it was missing at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer
	at ac.x.i0(SourceFile:110)
	at androidx.fragment.app.z.a0(Unknown Source:10)
	at ac.x.a0(SourceFile:45)
	at yb.p.k(SourceFile:8)
	at yb.a.j(SourceFile:38)
	at yb.a.d(Unknown Source:5)
	at ac.x.i0(SourceFile:68)
	... 28 more
Caused by: vb.d: Field 'playlistId' is required for type with serial name 'com.zionhuang.innertube.models.PlaylistPanelRenderer', but it was missing at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer
	at ac.x.i0(SourceFile:110)
	at androidx.fragment.app.z.a0(Unknown Source:10)
	at ac.x.a0(SourceFile:45)
	at com.zionhuang.innertube.models.Tabs$Tab$a.d(SourceFile:32)
	at ac.x.i0(SourceFile:68)
	... 34 more
Caused by: vb.d: Field 'playlistId' is required for type with serial name 'com.zionhuang.innertube.models.PlaylistPanelRenderer', but it was missing at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer
	at ac.x.i0(SourceFile:110)
	at androidx.fragment.app.z.U(Unknown Source:27)
	at com.zionhuang.innertube.models.Tabs$Tab$TabRenderer$a.d(SourceFile:55)
	at ac.x.i0(SourceFile:68)
	... 38 more
Caused by: vb.d: Field 'playlistId' is required for type with serial name 'com.zionhuang.innertube.models.PlaylistPanelRenderer', but it was missing at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer
	at ac.x.i0(SourceFile:110)
	at androidx.fragment.app.z.U(Unknown Source:27)
	at com.zionhuang.innertube.models.Tabs$Tab$TabRenderer$Content$a.d(SourceFile:36)
	at ac.x.i0(SourceFile:68)
	... 41 more
Caused by: vb.d: Field 'playlistId' is required for type with serial name 'com.zionhuang.innertube.models.PlaylistPanelRenderer', but it was missing at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer
	at ac.x.i0(SourceFile:110)
	at androidx.fragment.app.z.U(Unknown Source:27)
	at com.zionhuang.innertube.models.MusicQueueRenderer$a.d(SourceFile:32)
	at ac.x.i0(SourceFile:68)
	... 44 more
Caused by: vb.d: Field 'playlistId' is required for type with serial name 'com.zionhuang.innertube.models.PlaylistPanelRenderer', but it was missing at path: $.contents.singleColumnMusicWatchNextResultsRenderer.tabbedRenderer.watchNextTabbedResultsRenderer.tabs[0].tabRenderer.content.musicQueueRenderer.content.playlistPanelRenderer
	at ac.x.i0(SourceFile:110)
	at androidx.fragment.app.z.a0(Unknown Source:10)
	at ac.x.a0(SourceFile:45)
	at com.zionhuang.innertube.models.MusicQueueRenderer$Content$a.d(SourceFile:32)
	at ac.x.i0(SourceFile:68)
	... 47 more
Caused by: vb.d: Field 'playlistId' is required for type with serial name 'com.zionhuang.innertube.models.PlaylistPanelRenderer', but it was missing
	at e3.f.m(SourceFile:108)
	at com.zionhuang.innertube.models.PlaylistPanelRenderer.<init>(SourceFile:2)
	at com.zionhuang.innertube.models.PlaylistPanelRenderer$a.d(SourceFile:175)
	at ac.x.i0(SourceFile:68)
	... 51 more

**Comment by Vasanthanx** [comment]
How can use

**Comment by z-huang** [comment]
See #1653
