### ISSUE TITLE
Unable to play songs

### ISSUE THREAD

**Issue by benmax2309** [z-huang/music#1753]
### Checklist

- [X] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

Open the app 
Select any track 
Displaying red icon with text of unknown error 

### Expected behavior

Should play without any error 

### Actual behavior

Showing unknown error

### Screenshots/Screen recordings

![Screenshot_2024-12-18-16-57-31-046_com zionhuang music](https://github.com/user-attachments/assets/282018ac-52cf-4b6f-a554-65d357a5eb99)

### Logs

Unexpected exception loading stream
androidx.media3.common.PlaybackException: Unknown error
at com.zionhuang.music.playback.MusicService.createDataSourceFactory$lambda$35(MusicService.kt:639)
at com.zionhuang.music.playback.MusicService.$r8$lambda$sL6KryZX2JTGU40UEw4u6xwiCAg(Unknown Source:0)
at com.zionhuang.music.playback.MusicService$$ExternalSyntheticLambda4.resolveDataSpec(D8$$SyntheticClass:0)
at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:108)
at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1045)
at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)
Caused by: io.ktor.client.plugins.ServerResponseException: Server error(GET https://pipedapi.kavin.rocks/streams/heddkuA_rTY: 500 . Text: "{"error":"org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "Sign in to confirm that you're not a bot"\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.checkPlayabilityStatus(YoutubeStreamExtractor.java:898)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:784)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:67)\n\tat me.kavin.piped.server.handlers.StreamHandlers.lambda$streamsResponse$0(StreamHandlers.java:54)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\tat java.base/java.lang.VirtualThread.run(VirtualThread.java:329)\n","message":"Got error: "Sign in to confirm that you're not a bot""}"
at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:55)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

### InnerTune version

0.5.10

### Android version

Android 13

### Additional information

Please solve it as soon as possible

**Comment by 12kishansingh** [comment]
Unable to play new songs, the songs which i had played once recently are working well but if i'm playing new song which i'd not played showing "Unknown Error".
![WhatsApp Image 2024-12-18 at 17 20 28_765f030a](https://github.com/user-attachments/assets/c8738c2e-0ce7-4c0f-84bb-94de561fc756)

**Comment by rex186** [comment]
How to fix the unknown error
