### ISSUE TITLE
Trying to play music returns Unkown Error only when signed in 

### ISSUE THREAD

**Issue by AKoreanDumpling** [z-huang/music#1760]
### Checklist

- [x] I am able to reproduce the bug with the [latest debug version](https://github.com/z-huang/InnerTune/actions/workflows/build.yml).
- [X] I've checked that there is no open or closed issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Search or play any song, while being signed in

### Expected behavior

The song plays normally, regardless of being signed in or not

### Actual behavior

The cover is replaced with an explanation mark and a notice that an unknown error has occurred. Music doesn't play. Music plays when not signed in.

### Screenshots/Screen recordings

#1758 #1753 #1748

### Logs

#1753:

Unexpected exception loading stream
androidx.media3.common.PlaybackException: Unknown error
at com.zionhuang.music.playback.MusicService.createDataSourceFactory$lambda$35(MusicService.kt:639)
at com.zionhuang.music.playback.MusicService.$r8$lambda$sL6KryZX2JTGU40UEw4u6xwiCAg(Unknown Source:0)
at com.zionhuang.music.playback.MusicService$$ExternalSyntheticLambda4.resolveDataSpec(D8$$SyntheticClass:0)
at androidx.media3.datasource.ResolvingDataSource.open(ResolvingDataSource.java:108)
at androidx.media3.datasource.StatsDataSource.open(StatsDataSource.java:86)
at androidx.media3.exoplayer.source.ProgressiveMediaPeriod$ExtractingLoadable.load(ProgressiveMediaPeriod.java:1045)
at androidx.media3.exoplayer.upstream.Loader$LoadTask.run(Loader.java:421)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:644)
at java.lang.Thread.run(Thread.java:1012)
Caused by: io.ktor.client.plugins.ServerResponseException: Server error(GET https://pipedapi.kavin.rocks/streams/heddkuA_rTY: 500 . Text: "{"error":"org.schabi.newpipe.extractor.exceptions.ContentNotAvailableException: Got error: "Sign in to confirm that you're not a bot"\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.checkPlayabilityStatus(YoutubeStreamExtractor.java:898)\n\tat org.schabi.newpipe.extractor.services.youtube.extractors.YoutubeStreamExtractor.onFetchPage(YoutubeStreamExtractor.java:784)\n\tat org.schabi.newpipe.extractor.Extractor.fetchPage(Extractor.java:60)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:77)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:72)\n\tat org.schabi.newpipe.extractor.stream.StreamInfo.getInfo(StreamInfo.java:67)\n\tat me.kavin.piped.server.handlers.StreamHandlers.lambda$streamsResponse$0(StreamHandlers.java:54)\n\tat java.base/java.util.concurrent.FutureTask.run(FutureTask.java:317)\n\tat java.base/java.lang.VirtualThread.run(VirtualThread.java:329)\n","message":"Got error: "Sign in to confirm that you're not a bot""}"
at io.ktor.client.plugins.DefaultResponseValidationKt$addDefaultResponseValidation$1$1.invokeSuspend(DefaultResponseValidation.kt:55)
at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)

### InnerTune version

0.5.10

### Android version

Android 12, 13, 14

### Additional information

This is an attempted consolidation of previous same issue bug reports

**Comment by gechoto** [comment]
Please close this and avoid creating duplicates in the future. There are already enough of these reports.

**Comment by Mizumiyaakio** [comment]
> Please close this and avoid creating duplicates in the future. There are already enough of these reports.

It not a bug, it actually Google itself. I try multiple app like this ritune etc, everything got blocka

**Comment by AKoreanDumpling** [comment]
> Please close this and avoid creating duplicates in the future. There are already enough of these reports.

How would you recommend consolidation for multiple issues? This was just a summary to make it easier to differentiate the please log in issue from the unknown error issue.

**Comment by RougeParrot** [comment]
https://www.reddit.com/r/fossdroid/comments/1hgwd48/innertune_not_working_temporary_fix/?utm_source=share&utm_medium=mweb3x&utm_name=mweb3xcss&utm_term=1&utm_content=share_button
