### ISSUE TITLE
App crashes when trying to play songs

### ISSUE THREAD

**Issue by eumunhoz** [z-huang/music#6]
Hello!

I've just found out about this amazing app! I've been waiting for someone to develop a music-focused application based on the NewPipe Extractor, and you've managed to do that with a simple, great user interface!

Unfortunately I'm not able to play songs on my device. When trying to play songs from the Explore section and even downloaded ones the app crashes instantly. Sometimes the song starts playing but the app crashes anyway. I believe the problem is somehow related to my Android version, 12. I'm sending you the crash log I got:

```
time: 1649558544066
msg: java.lang.IllegalArgumentException: com.zionhuang.music: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
stacktrace: java.lang.IllegalArgumentException: com.zionhuang.music: Targeting S+ (version 31 and above) requires that one of FLAG_IMMUTABLE or FLAG_MUTABLE be specified when creating a PendingIntent.
Strongly consider using FLAG_IMMUTABLE, only use FLAG_MUTABLE if some functionality depends on the PendingIntent being mutable, e.g. if it needs to be used with inline replies or bubbles.
	at android.app.PendingIntent.checkFlags(PendingIntent.java:375)
	at android.app.PendingIntent.getActivityAsUser(PendingIntent.java:458)
	at android.app.PendingIntent.getActivity(PendingIntent.java:444)
	at android.app.PendingIntent.getActivity(PendingIntent.java:408)
	at com.zionhuang.music.playback.SongPlayer$playerNotificationManager$1.createCurrentContentIntent(SongPlayer.kt:5)
	at com.google.android.exoplayer2.ui.PlayerNotificationManager.startOrUpdateNotification(PlayerNotificationManager.java:96)
	at com.google.android.exoplayer2.ui.PlayerNotificationManager$$ExternalSyntheticLambda0.handleMessage(R8$$SyntheticClass:5)
	at android.os.Handler.dispatchMessage(Handler.java:102)
	at android.os.Looper.loopOnce(Looper.java:201)
	at android.os.Looper.loop(Looper.java:288)
	at android.app.ActivityThread.main(ActivityThread.java:7839)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:548)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1003)
```

Thanks!

**Comment by z-huang** [comment]
Thanks for the positive feedback! I'll keep perfecting the app.
The cause of bug might be a parameter of a flag I missed when handling the click action of the media notification. I'll use an Android emulator to check further. Thanks for reporting the bug.

**Comment by z-huang** [comment]
Adding missing FLAG_IMMUTABLE may fix the issue: 7214b3db66a914947080eeda1e649d6d8e895c59
