### ISSUE TITLE
App crashes when finding songs

### ISSUE THREAD

**Issue by airon90** [z-huang/music#78]
### Checklist

- [X] I am able to reproduce the bug with the [latest version](https://github.com/z-huang/music/releases/latest).
- [X] I've checked that there is no issue about this bug.
- [X] This issue contains only one bug.
- [X] The title of this issue accurately describes the bug.

### Steps to reproduce the bug

1. Have 3k songs in library
2. Scroll the library by name

### Expected behavior

Scroll library by letter

### Actual behavior

App crashes

### Logs

```[airon@aironpc ~]$ adb logcat --pid=$(adb shell pidof -s com.zionhuang.music)
--------- beginning of main
06-07 09:44:28.432 20327 20327 E zionhuang.musi: Unknown bits set in runtime_flags: 0x800000
06-07 09:44:28.437 20327 20327 E zionhuang.musi: Not starting debugger since process cannot load the jdwp agent.
06-07 09:44:28.509 20327 20327 I Perf    : Connecting to perf service.
06-07 09:44:28.520 20327 20327 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-07 09:44:28.521 20327 20327 D NetworkSecurityConfig: No Network Security Config specified, using platform default
06-07 09:44:28.529 20327 20327 D WM-WrkMgrInitializer: Initializing WorkManager with default configuration.
06-07 09:44:28.533 20327 20327 I TetheringManager: registerTetheringEventCallback:com.zionhuang.music
06-07 09:44:28.631 20327 20327 D DecorView[]: getWindowModeFromSystem  windowmode is 1
06-07 09:44:28.631 20327 20327 D DecorView: createDecorCaptionView windowingMode:1 mWindowMode 1 isFullscreen: true
06-07 09:44:28.640 20327 20327 D MainActivity: android.intent.action.MAIN null
06-07 09:44:28.748 20327 20327 W DataBinding: Setting the fragment as the LifecycleOwner might cause memory leaks because views lives shorter than the Fragment. Consider using Fragment's view lifecycle
--------- beginning of system
06-07 09:44:28.755 20327 20327 W Activity: Slow Operation: Activity com.zionhuang.music/.ui.activities.MainActivity onStart took 111ms
06-07 09:44:28.767 20327 20327 D DecorView[]: getWindowModeFromSystem  windowmode is 1
06-07 09:44:28.773 20327 20327 W Looper  : PerfMonitor looperActivity : package=com.zionhuang.music/.ui.activities.MainActivity time=0ms latency=301ms running=0ms  procState=2 ClientTransaction{ callbacks=[android.app.servertransaction.TopResumedActivityChangeItem] } historyMsgCount=2 (msgIndex=1 wall=91ms seq=2 running=75ms runnable=7ms late=4ms h=android.app.ActivityThread$H w=110) (msgIndex=2 wall=222ms seq=3 running=196ms runnable=9ms late=80ms h=android.app.ActivityThread$H w=159)
06-07 09:44:28.797 20327 20327 I ExoPlayerImpl: Init 85d7095 [ExoPlayerLib/2.16.1] [willow, Redmi Note 8T, Xiaomi, 30]
06-07 09:44:28.801 20327 20327 E libc    : Access denied finding property "ro.vendor.df.effect.conflict"
06-07 09:44:28.801 20327 20327 E libc    : Access denied finding property "ro.vendor.knock.type"
06-07 09:44:28.850 20327 20349 I AdrenoGLES-0: QUALCOMM build                   : 03e27f8, I326e6aff90
06-07 09:44:28.850 20327 20349 I AdrenoGLES-0: Build Date                       : 11/02/20
06-07 09:44:28.850 20327 20349 I AdrenoGLES-0: OpenGL ES Shader Compiler Version: EV031.32.02.04
06-07 09:44:28.850 20327 20349 I AdrenoGLES-0: Local Branch                     : mybrancheb1d781c-1a78-f1f4-8c78-ac1f6bcc2cee
06-07 09:44:28.850 20327 20349 I AdrenoGLES-0: Remote Branch                    : quic/gfx-adreno.lnx.1.0.r116-rel
06-07 09:44:28.850 20327 20349 I AdrenoGLES-0: Remote Branch                    : NONE
06-07 09:44:28.850 20327 20349 I AdrenoGLES-0: Reconstruct Branch               : NOTHING
06-07 09:44:28.850 20327 20349 I AdrenoGLES-0: Build Config                     : S P 10.0.7 AArch64
06-07 09:44:28.850 20327 20349 I AdrenoGLES-0: Driver Path                      : /vendor/lib64/egl/libGLESv2_adreno.so
06-07 09:44:28.857 20327 20349 I AdrenoGLES-0: PFP: 0x016ee190, ME: 0x00000000
06-07 09:44:28.901 20327 20349 E LB      : fail to open file: No such file or directory
06-07 09:44:28.907 20327 20327 D CompatibilityChangeReporter: Compat change id reported: 147600208; UID 10005; state: ENABLED
06-07 09:44:28.952 20327 20327 E zionhuang.musi: Invalid ID 0x00000000.
06-07 09:44:28.955 20327 20327 D miuisdk : current sdk level is 24
06-07 09:44:31.223 20327 20327 W Choreographer: Frame time is 0.048569 ms in the future!  Check that graphics HAL is generating vsync timestamps using the correct timebase.
06-07 09:44:37.136 20327 20327 V MiuiFrameworkFactory: get AllImpl object = android.common.MiuiFrameworkFactoryImpl@2a5581
06-07 09:44:37.144 20327 20327 W MirrorManager: this model don't Support
06-07 09:44:38.539 20327 20327 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
06-07 09:44:38.540 20327 20327 I chatty  : uid=10005(com.zionhuang.music) identical 8 lines
06-07 09:44:38.540 20327 20327 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
06-07 09:44:38.791 20327 20349 D OpenGLRenderer: endAllActiveAnimators on 0xb400007d3ce43000 (MenuPopupWindow$MenuDropDownListView) with handle 0xb400007e3ba32f40
06-07 09:44:38.811 20327 20327 D DefaultSelectionTracker: Ignoring onDataSetChange. No active selection.
06-07 09:44:40.749 20327 20327 D AndroidRuntime: Shutting down VM
--------- beginning of crash
06-07 09:44:40.749 20327 20327 E AndroidRuntime: FATAL EXCEPTION: main
06-07 09:44:40.749 20327 20327 E AndroidRuntime: Process: com.zionhuang.music, PID: 20327
06-07 09:44:40.749 20327 20327 E AndroidRuntime: java.lang.NullPointerException: Parameter specified as non-null is null: method com.zionhuang.music.databinding.ItemSongBindingImpl.executeBindings, parameter id
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at com.zionhuang.music.databinding.ItemSongBindingImpl.executeBindings(ItemSongBindingImpl.java:14)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at androidx.databinding.ViewDataBinding.executePendingBindings(ViewDataBinding.java:5)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at androidx.databinding.ViewDataBinding$7.run(ViewDataBinding.java:19)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at androidx.databinding.ViewDataBinding$8.doFrame(ViewDataBinding.java:3)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1056)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at android.view.Choreographer.doCallbacks(Choreographer.java:880)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at android.view.Choreographer.doFrame(Choreographer.java:809)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1043)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at android.os.Handler.handleCallback(Handler.java:938)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:99)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:236)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:8037)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:656)
06-07 09:44:40.749 20327 20327 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:967)
06-07 09:44:40.800 20327 20327 I Process : Sending signal. PID: 20327 SIG: 9
```

### Music version

Latest F-Droid

### Android version

MIUI 12.5

### Additional information

#38 seems not to be fixed correctly

**Comment by z-huang** [comment]
That seems to be due to the fastscrolling feature. I'll fetch all songs instead of using Paging source if efficiency permits, which I think will solve the issue.
